#==========================swagger 访问接口==================================
#           http://${ip}:10131/swagger-ui/index.html                      #
#==========================================================================
server:
  port: 10200
spring:
  ##################################################################################################
  #                               nacos
  #                           192.168.60.119:8848
  #                           192.168.188.106:8848
  ##################################################################################################
  application:
    name: redisson2Service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.188.106:8848
        namespace: cc8561c5-2d87-4db8-95fc-ddc0fb03e563
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        file-extension: yaml
        prefix: ${spring.application.name}
  profiles:
    active: dev
  ##################################################################################################
  #                               redisson 单服务器配置
  #
  ##################################################################################################
redisson:
  single:
    idleConnectionTimeout: 10000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    password: NXMz5MpQ8BTTQ4wRPTk7
    subscriptionsPerConnection: 5
    clientName: null
    address: redis://192.168.188.104:6379
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    connectionMinimumIdleSize: 32
    connectionPoolSize: 64
    database: 13
    dnsMonitoringInterval: 5000
    threads: 0
    nettyThreads: 0
    codec: org.redisson.codec.JsonJacksonCodec
    #codec: !<org.redisson.codec.FstCodec> {}
    transportMode: "NIO"
############################################################################################
#                               调试选项(热加载)
#                path:  路径
#                maxHistory:   本地打印保存时间
#                sendKafka： 设置kafka日记收集的级别,如需收集更多的级别,取消注释即可
#                printFile： 设置本地日记打印的级别,如不需要打印，注释即可
#############################################################################################
mind.links.logger:
  topic: logger
  path: ${spring.application.name}
  maxHistory: 30
  sendKafka:
    #level1: DEBUG
#    level2: INFO
    #level3: WARN
#    level4: ERROR
  printFile:
  #level1: DEBUG
  #level2: INFO
  #level3: WARN
  #level4: ERROR
# 是否开始swagger api文档 true or false
swagger:
  enable: true
#  是否直接在控制台打印异常  true or false
exception:
  printStackTrace: true
