##############################################################################################
#                   http://localhost:39000/druid/login.html
#############################################################################################
server:
  port: 39000
spring:
  application:
    name: elasticsearch
  #####################################  elasticsearch  ###############################################
  # ssl 主机名称校验，是否采用default配置，
  # 如果指定为default，就采用DefaultHostnameVerifier,否则采用 SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER
  # 测试： 192.168.60.119:9200
  #####################################################################################################
  elasticsearch:
    bboss:
      elasticPassword:
      elasticUser:
      elasticsearch:
        dateFormat: yyyy.MM.dd
        discoverHost: false
        rest:
          hostNames: 192.168.60.119:9200
        scrollBlockedWaitTimeout: 0
        scrollThreadCount: 200
        scrollThreadQueue: 200
        showTemplate: true
        sliceScrollBlockedWaitTimeout: 0
        sliceScrollThreadCount: 100
        sliceScrollThreadQueue: 100
        timeZone: Asia/Shanghai
      http:
        connectionRequestTimeout: 5000
        customHttpRequestRetryHandler: org.frameworkset.spi.remote.http.ConnectionResetHttpRequestRetryHandler
        defaultMaxPerRoute: 200
        hostnameVerifier:
        keepAlive: 3600000
        keyPassword:
        keystore:
        maxHeaderCount: 200
        maxLineLength: -1
        maxTotal: 400
        retryTime: 1
        retryInterval: 1000
        soKeepAlive: false
        soReuseAddress: false
        staleConnectionCheckEnabled: false
        timeToLive: 3600000
        timeoutConnection: 5000
        timeoutSocket: 5000
        validateAfterInactivity: 2000
############################################################################################
#                               调试选项(热加载)
#                path:  路径
#                log:   保存时间
#                send： 设置日记收集的级别,如需收集更多的级别,取消注释即可
#############################################################################################
mind.links.logger:
  path: log
  maxHistory: 30
  send:
    #   level1: DEBUG
    level2: INFO
    level3: WARN
    level4: ERROR

